import type { Category, Material, Unit } from "@/lib/types";

export type SeedCatalog = {
  name: string;
  category: Category;
  material: Material;
  gauge: string;
  unit: Unit;
  materialUnitCost: number;
  laborHoursPerUnit: number;
  wastePct: number;
  notes: string;
};

export const SEED_CATALOG: SeedCatalog[] = [
  {
    name: "24ga Galvalume standing seam panel",
    category: "roofing",
    material: "galvalume",
    gauge: "24 ga",
    unit: "sf",
    materialUnitCost: 4.85,
    laborHoursPerUnit: 0.08,
    wastePct: 10,
    notes: "1.5\" mechanical seam, 16\" pan",
  },
  {
    name: "16oz copper standing seam panel",
    category: "roofing",
    material: "copper",
    gauge: "16 oz",
    unit: "sf",
    materialUnitCost: 18.4,
    laborHoursPerUnit: 0.12,
    wastePct: 12,
    notes: "Double-lock, 20\" pan",
  },
  {
    name: "Rheinzink standing seam 0.7mm",
    category: "roofing",
    material: "zinc",
    gauge: "0.7 mm",
    unit: "sf",
    materialUnitCost: 14.2,
    laborHoursPerUnit: 0.12,
    wastePct: 12,
    notes: "PrePATINA blue-grey",
  },
  {
    name: "24ga galvalume drip edge",
    category: "flashing",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 3.2,
    laborHoursPerUnit: 0.08,
    wastePct: 8,
    notes: "",
  },
  {
    name: "24ga step flashing",
    category: "flashing",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 4.1,
    laborHoursPerUnit: 0.12,
    wastePct: 10,
    notes: "5x7 typical",
  },
  {
    name: "16oz copper valley flashing",
    category: "flashing",
    material: "copper",
    gauge: "16 oz",
    unit: "lf",
    materialUnitCost: 22,
    laborHoursPerUnit: 0.16,
    wastePct: 10,
    notes: "W-valley, soldered laps",
  },
  {
    name: "24ga counter flashing",
    category: "flashing",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 5.4,
    laborHoursPerUnit: 0.1,
    wastePct: 8,
    notes: "Reglet or surface-mount",
  },
  {
    name: "16oz copper through-wall flashing",
    category: "flashing",
    material: "copper",
    gauge: "16 oz",
    unit: "lf",
    materialUnitCost: 18,
    laborHoursPerUnit: 0.12,
    wastePct: 8,
    notes: "With drip and receiver",
  },
  {
    name: "24ga head / sill flashing",
    category: "flashing",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 4.8,
    laborHoursPerUnit: 0.09,
    wastePct: 8,
    notes: "",
  },
  {
    name: "24ga chimney cricket",
    category: "custom",
    material: "galvalume",
    gauge: "24 ga",
    unit: "ea",
    materialUnitCost: 185,
    laborHoursPerUnit: 3,
    wastePct: 5,
    notes: "Shop-built, sized to chimney",
  },
  {
    name: "24ga prefinished coping cap",
    category: "coping",
    material: "prepainted_steel",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 18.5,
    laborHoursPerUnit: 0.25,
    wastePct: 8,
    notes: "Kynar, with continuous cleat",
  },
  {
    name: "16oz copper coping cap",
    category: "coping",
    material: "copper",
    gauge: "16 oz",
    unit: "lf",
    materialUnitCost: 42,
    laborHoursPerUnit: 0.3,
    wastePct: 8,
    notes: "Soldered joints, standing seam look",
  },
  {
    name: "Continuous coping cleat",
    category: "coping",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 3.8,
    laborHoursPerUnit: 0.05,
    wastePct: 5,
    notes: "",
  },
  {
    name: "6\" K-style galvalume gutter",
    category: "gutter",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 8.2,
    laborHoursPerUnit: 0.15,
    wastePct: 8,
    notes: "Hidden hanger",
  },
  {
    name: "6\" half-round copper gutter",
    category: "gutter",
    material: "copper",
    gauge: "16 oz",
    unit: "lf",
    materialUnitCost: 38,
    laborHoursPerUnit: 0.2,
    wastePct: 8,
    notes: "Double bead, soldered",
  },
  {
    name: "4x5 downspout, galvalume",
    category: "gutter",
    material: "galvalume",
    gauge: "24 ga",
    unit: "lf",
    materialUnitCost: 6.4,
    laborHoursPerUnit: 0.1,
    wastePct: 5,
    notes: "",
  },
  {
    name: "4\" round copper downspout",
    category: "gutter",
    material: "copper",
    gauge: "16 oz",
    unit: "lf",
    materialUnitCost: 28,
    laborHoursPerUnit: 0.12,
    wastePct: 5,
    notes: "With elbows and outlets",
  },
  {
    name: "Gutter hanger / strap",
    category: "gutter",
    material: "none",
    gauge: "",
    unit: "ea",
    materialUnitCost: 4.5,
    laborHoursPerUnit: 0.05,
    wastePct: 0,
    notes: "24\" o.c. typical",
  },
  {
    name: "Copper conductor head",
    category: "gutter",
    material: "copper",
    gauge: "16 oz",
    unit: "ea",
    materialUnitCost: 185,
    laborHoursPerUnit: 0.6,
    wastePct: 0,
    notes: "Shop-built leader head",
  },
  {
    name: "24ga corrugated wall panel",
    category: "wall_panel",
    material: "galvalume",
    gauge: "24 ga",
    unit: "sf",
    materialUnitCost: 3.9,
    laborHoursPerUnit: 0.06,
    wastePct: 10,
    notes: "7/8\" corrugation",
  },
  {
    name: "22ga prefinished wall panel",
    category: "wall_panel",
    material: "prepainted_steel",
    gauge: "22 ga",
    unit: "sf",
    materialUnitCost: 7.8,
    laborHoursPerUnit: 0.08,
    wastePct: 10,
    notes: "Concealed fastener",
  },
  {
    name: "Shop brake / fab time",
    category: "labor",
    material: "none",
    gauge: "",
    unit: "hr",
    materialUnitCost: 0,
    laborHoursPerUnit: 1,
    wastePct: 0,
    notes: "Custom folding, welding, solder",
  },
  {
    name: "Field install labor",
    category: "labor",
    material: "none",
    gauge: "",
    unit: "hr",
    materialUnitCost: 0,
    laborHoursPerUnit: 1,
    wastePct: 0,
    notes: "Crew on site",
  },
  {
    name: "Ice & water shield",
    category: "other",
    material: "none",
    gauge: "",
    unit: "sf",
    materialUnitCost: 0.85,
    laborHoursPerUnit: 0.015,
    wastePct: 8,
    notes: "Eaves, valleys, penetrations",
  },
  {
    name: "Synthetic underlayment",
    category: "other",
    material: "none",
    gauge: "",
    unit: "sf",
    materialUnitCost: 0.32,
    laborHoursPerUnit: 0.01,
    wastePct: 8,
    notes: "",
  },
  {
    name: "Stainless fasteners / clips",
    category: "other",
    material: "stainless",
    gauge: "",
    unit: "ea",
    materialUnitCost: 0.85,
    laborHoursPerUnit: 0,
    wastePct: 5,
    notes: "Per clip or screw",
  },
];

export type SeedCustomer = {
  name: string;
  contactName: string;
  email: string;
  phone: string;
  address: string;
};

export const SEED_CUSTOMERS: SeedCustomer[] = [
  {
    name: "Pacific Ridge Construction",
    contactName: "Dana Ellison",
    email: "dana@pacificridge.example",
    phone: "(503) 555-0142",
    address: "2100 NW Yeon Ave, Portland, OR",
  },
  {
    name: "Northshore Builders",
    contactName: "Marcus Chen",
    email: "mchen@northshore.example",
    phone: "(206) 555-0194",
    address: "88 Western Ave, Seattle, WA",
  },
  {
    name: "Meridian Property Group",
    contactName: "Elena Voss",
    email: "evoss@meridianpg.example",
    phone: "(971) 555-0166",
    address: "111 SW 5th Ave, Portland, OR",
  },
  {
    name: "Walsh & Sons GC",
    contactName: "Tom Walsh",
    email: "tom@walshsons.example",
    phone: "(541) 555-0118",
    address: "402 Oak St, Eugene, OR",
  },
];
